FROM nvidia/cuda:10.0-cudnn7-runtime

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y gcc build-essential tesseract-ocr libxtst6 libglib2.0-0 libsm6 libfontconfig1 libxrender1 \
  python3 python3-tk python3-pip
  
RUN pip3 install tensorflow-gpu==1.13.1 opencv-python pytesseract
