FROM python:3.7-slim

RUN apt-get update \
  && apt-get install -y tesseract-ocr libxtst6 libglib2.0-0 libsm6 libfontconfig1 libxrender1 
  
RUN pip3 install tensorflow-gpu==1.13.1 opencv-python pytesseract
